### DISCUSSION TITLE
关于docker-compose方式部署doris

### DISCUSSION THREAD

**Discussion by lzzcj** [apache/doris#16437] [A - General / Q&A] [answered]
请问什么时候会完善docker-compose部署方式？这种方式部署是否适合生产环境？

**Comment by zy-kkk** [comment, marked as answer]
docker-compose部署方式仅适用于测试，不适合生产环境部署
如果想测试可参考如下模板

Doris On Docker - DockereCompose 模板
当前提供的是 1.2.1 版本的镜像，以下脚本将会生成 3FE 3BE 的 Docker 集群，最小适用机器为2C8G
使用方式是，将以下代码保存至服务器，命名为 docker-compose.yaml，然后在该目录下执行 docker-compose up -d 即可
```
version: '3'
services:
  docker-fe-01:
    image: "apache/doris:1.2.1-fe-x86_64"
    container_name: "doris-fe-01"
    hostname: "fe-01"
    environment:
      - FE_SERVERS=fe1:[172.20.80.2:9010](http://172.20.80.2:9010/),fe2:[172.20.80.3:9010](http://172.20.80.3:9010/),fe3:[172.20.80.4:9010](http://172.20.80.4:9010/)
      - FE_ID=1
    ports:
      - 8031:8030
      - 9031:9030
    volumes:
      - /data/fe-01/doris-meta:/opt/apache-doris/fe/doris-meta
      - /data/fe-01/conf:/opt/apache-doris/fe/conf
      - /data/fe-01/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: [172.20.80.2](http://172.20.80.2/)
  docker-fe-02:
    image: "apache/doris:1.2.1-fe-x86_64"
    container_name: "doris-fe-02"
    hostname: "fe-02"
    environment:
      - FE_SERVERS=fe1:[172.20.80.2:9010](http://172.20.80.2:9010/),fe2:[172.20.80.3:9010](http://172.20.80.3:9010/),fe3:[172.20.80.4:9010](http://172.20.80.4:9010/)
      - FE_ID=2
    ports:
      - 8032:8030
      - 9032:9030
    volumes:
      - /data/fe-02/doris-meta:/opt/apache-doris/fe/doris-meta
      - /data/fe-02/conf:/opt/apache-doris/fe/conf
      - /data/fe-02/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: [172.20.80.3](http://172.20.80.3/)
  docker-fe-03:
    image: "apache/doris:1.2.1-fe-x86_64"
    container_name: "doris-fe-03"
    hostname: "fe-03"
    environment:
      - FE_SERVERS=fe1:[172.20.80.2:9010](http://172.20.80.2:9010/),fe2:[172.20.80.3:9010](http://172.20.80.3:9010/),fe3:[172.20.80.4:9010](http://172.20.80.4:9010/)
      - FE_ID=3
    ports:
      - 8033:8030
      - 9033:9030
    volumes:
      - /data/fe-03/doris-meta:/opt/apache-doris/fe/doris-meta
      - /data/fe-03/conf:/opt/apache-doris/fe/conf
      - /data/fe-03/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: [172.20.80.4](http://172.20.80.4/)
  docker-be-01:
    image: "apache/doris:1.2.1-be-x86_64"
    container_name: "doris-be-01"
    hostname: "be-01"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:[172.20.80.2:9010](http://172.20.80.2:9010/),fe2:[172.20.80.3:9010](http://172.20.80.3:9010/),fe3:[172.20.80.4:9010](http://172.20.80.4:9010/)
      - BE_ADDR=[172.20.80.5:9050](http://172.20.80.5:9050/)
    ports:
      - 8041:8040
    volumes:
      - /data/be-01/storage:/opt/apache-doris/be/storage
      - /data/be-01/conf:/opt/apache-doris/be/conf
      - /data/be-01/script:/docker-entrypoint-initdb.d
      - /data/be-01/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: [172.20.80.5](http://172.20.80.5/)
  docker-be-02:
    image: "apache/doris:1.2.1-be-x86_64"
    container_name: "doris-be-02"
    hostname: "be-02"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:[172.20.80.2:9010](http://172.20.80.2:9010/),fe2:[172.20.80.3:9010](http://172.20.80.3:9010/),fe3:[172.20.80.4:9010](http://172.20.80.4:9010/)
      - BE_ADDR=[172.20.80.6:9050](http://172.20.80.6:9050/)
    ports:
      - 8042:8040
    volumes:
      - /data/be-02/storage:/opt/apache-doris/be/storage
      - /data/be-02/conf:/opt/apache-doris/be/conf
      - /data/be-02/script:/docker-entrypoint-initdb.d
      - /data/be-02/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: [172.20.80.6](http://172.20.80.6/)
  docker-be-03:
    image: "apache/doris:1.2.1-be-x86_64"
    container_name: "doris-be-03"
    hostname: "be-03"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:[172.20.80.2:9010](http://172.20.80.2:9010/),fe2:[172.20.80.3:9010](http://172.20.80.3:9010/),fe3:[172.20.80.4:9010](http://172.20.80.4:9010/)
      - BE_ADDR=[172.20.80.7:9050](http://172.20.80.7:9050/)
    ports:
      - 8043:8040
    volumes:
      - /data/be-03/storage:/opt/apache-doris/be/storage
      - /data/be-03/conf:/opt/apache-doris/be/conf
      - /data/be-03/script:/docker-entrypoint-initdb.d
      - /data/be-03/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: [172.20.80.7](http://172.20.80.7/)
networks:
  doris_net:
    ipam:
      config:
        - subnet: [172.20.80.0/16](http://172.20.80.0/16)
```
