### DISCUSSION TITLE
Doris Profile 问题

### DISCUSSION THREAD

**Discussion by LCehoennardo** [apache/doris#16487] [A - General / Q&A]
我们执行了一个多表 Join SQL，耗时26s，分析profile，发现其中一个scan node就用了19s，感觉很不合理。如果单独查询这张表，根本不需要这么多时间，如果把其中的 left join 改为 inner join，整个查询不到 10s 即可完成。
不是说profile能分析出哪里耗时最长，但感觉这个分析结果不对啊。
还望有大佬解答一下！

profile如下（其中`OLAP_SCAN_NODE (id=1)`耗时19s）：
```
Execution Profile 791b2673d2424a5c-8c2453d39f1ad379:(Active: 26s647ms, % non-child: 100.00%)
    Fragment 0:
      Instance 791b2673d2424a5c-8c2453d39f1ad37b (host=TNetworkAddress(hostname:10.0.49.81, port:9060)):(Active: 26s622ms, % non-child: 0.00%)
         - FragmentCpuTime: 281.855us
         - MemoryLimit: 4.00 GB
         - PeakMemoryUsage: 20.00 KB
         - RowsProduced: 10
        BlockMgr:
           - BlockWritesOutstanding: 0
           - BlocksCreated: 0
           - BlocksRecycled: 0
           - BufferedPins: 0
           - BytesWritten: 0.00 
           - MaxBlockSize: 8.00 MB
           - TotalBufferWaitTime: 0ns
           - TotalEncryptionTime: 0ns
           - TotalIntegrityCheckTime: 0ns
           - TotalReadBlockTime: 0ns
        DataBufferSender (dst_fragment_instance_id=791b2673d2424a5c-8c2453d39f1ad37b):
           - AppendBatchTime: 199.66us
             - ResultSendTime: 171.6us
             - TupleConvertTime: 17.845us
           - NumSentRows: 10
        EXCHANGE_NODE (id=8):(Active: 26s622ms, % non-child: 99.91%)
           - BytesReceived: 0.00 
           - ConvertRowBatchTime: 0ns
           - DataArrivalWaitTime: 26s622ms
           - DeserializeRowBatchTimer: 0ns
           - FirstBatchArrivalWaitTime: 26s622ms
           - MergeGetNext: 137.696us
           - MergeGetNextBatch: 136.508us
           - PeakMemoryUsage: 12.00 KB
           - RowsReturned: 10
           - RowsReturnedRate: 0
           - SendersBlockedTotalTimer(*): 0ns
    Fragment 1:
      Instance 791b2673d2424a5c-8c2453d39f1ad37a (host=TNetworkAddress(hostname:10.0.49.81, port:9060)):(Active: 26s622ms, % non-child: 0.00%)
         - FragmentCpuTime: 229.544ms
         - MemoryLimit: 4.00 GB
         - PeakMemoryUsage: 625.18 MB
         - RowsProduced: 11
        BlockMgr:
           - BlockWritesOutstanding: 0
           - BlocksCreated: 0
           - BlocksRecycled: 0
           - BufferedPins: 0
           - BytesWritten: 0.00 
           - MaxBlockSize: 8.00 MB
           - TotalBufferWaitTime: 0ns
           - TotalEncryptionTime: 0ns
           - TotalIntegrityCheckTime: 0ns
           - TotalReadBlockTime: 0ns
        DataStreamSender (dst_id=8, dst_fragments=[791b2673d2424a5c-8c2453d39f1ad37b]):(Active: 52.402us, % non-child: 0.00%)
           - BytesSent: 0.00 
           - IgnoreRows: 0
           - LocalBytesSent: 2.59 KB
           - OverallThroughput: 0.0 /sec
           - PeakMemoryUsage: 816.00 B
           - SerializeBatchTime: 0ns
           - UncompressedRowBatchSize: 0.00 
        SORT_NODE (id=7):(Active: 26s622ms, % non-child: 0.02%)
           - PeakMemoryUsage: 620.00 KB
           - RowsReturned: 11
           - RowsReturnedRate: 0
          HASH_JOIN_NODE (id=6):(Active: 26s618ms, % non-child: 0.00%)
             - ExecOption: Hash Table Built Asynchronously
             - BuildBuckets: 8.192K (8192)
             - BuildRows: 4.226K (4226)
             - BuildTime: 36.952ms
             - HashTableMaxList: 5
             - HashTableMinList: 1
             - LoadFactor: 4600972377126338600.00
             - PeakMemoryUsage: 1.57 MB
             - ProbeRows: 3.553K (3553)
             - ProbeTime: 675.140us
             - PushDownComputeTime: 0ns
             - PushDownTime: 0ns
             - RowsReturned: 3.553K (3553)
             - RowsReturnedRate: 133
            OLAP_SCAN_NODE (id=5):(Active: 36.507ms, % non-child: 0.14%)
               - BatchQueueWaitTime: 36.308ms
               - BytesRead: 220.34 KB
               - NumDiskAccess: 1
               - NumScanners: 1
               - PeakMemoryUsage: 0.00 
               - RowsRead: 4.226K (4226)
               - RowsReturned: 4.226K (4226)
               - RowsReturnedRate: 115.756K /sec
               - ScannerBatchWaitTime: 36.244ms
               - ScannerSchedCount : 1
               - ScannerWorkerWaitTime: 25.292us
               - TabletCount : 1
               - TotalReadThroughput: 0.0 /sec
              OlapScanner:
                 - VconjunctExprTree: null
                 - BlockConvertTime: 195.112us
                 - BlockFetchTime: 7.514ms
                 - ReaderInitTime: 7.166ms
                 - RowsDelFiltered: 0
                 - RowsPushedCondFiltered: 0
                 - ScanCpuTime: 36.207ms
                 - ScanTime: 28.649ms
                 - ShowHintsTime_V1: 0ns
                SegmentIterator:
                   - BitmapIndexFilterTimer: 1.863us
                   - BlockLoadTime: 7.243ms
                   - BlockSeekCount: 58
                   - BlockSeekTime: 3.285ms
                   - BlocksLoad: 6
                   - CachedPagesNum: 0
                   - CompressedBytesRead: 1.27 MB
                   - DecompressorTimer: 1.728ms
                   - IOTimer: 882.877us
                   - IndexLoadTime_V1: 0ns
                   - NumSegmentFiltered: 12
                   - NumSegmentTotal: 14
                   - RawRowsRead: 4.249K (4249)
                   - RowsBitmapIndexFiltered: 0
                   - RowsBloomFilterFiltered: 6.591864M (6591864)
                   - RowsConditionsFiltered: 0
                   - RowsKeyRangeFiltered: 6.646603M (6646603)
                   - RowsStatsFiltered: 38.234K (38234)
                   - RowsVectorPredFiltered: 0
                   - TotalPagesNum: 18
                   - UncompressedBytesRead: 1.75 MB
                   - VectorPredEvalTime: 66.453us
            HASH_JOIN_NODE (id=4):(Active: 26s617ms, % non-child: 2.03%)
               - ExecOption: Hash Table Built Asynchronously
               - BuildBuckets: 1.048576M (1048576)
               - BuildRows: 1.365221M (1365221)
               - BuildTime: 6s811ms
               - HashTableMaxList: 10
               - HashTableMinList: 1
               - LoadFactor: 4604730636719095800.00
               - PeakMemoryUsage: 562.64 MB
               - ProbeRows: 3.553K (3553)
               - ProbeTime: 3.184ms
               - PushDownComputeTime: 218.415ms
               - PushDownTime: 10.683us
               - RowsReturned: 3.553K (3553)
               - RowsReturnedRate: 133
              OLAP_SCAN_NODE (id=3):(Active: 6s273ms, % non-child: 23.54%)
                 - BatchQueueWaitTime: 6s268ms
                 - BytesRead: 109.93 MB
                 - NumDiskAccess: 1
                 - NumScanners: 1
                 - PeakMemoryUsage: 0.00 
                 - RowsRead: 1.4014M (1401400)
                 - RowsReturned: 1.365221M (1365221)
                 - RowsReturnedRate: 217.61K /sec
                 - ScannerBatchWaitTime: 6s585ms
                 - ScannerSchedCount : 86
                 - ScannerWorkerWaitTime: 4.119ms
                 - TabletCount : 1
                 - TotalReadThroughput: 0.0 /sec
                OlapScanner:
                   - VconjunctExprTree: null
                   - BlockConvertTime: 91.649ms
                   - BlockFetchTime: 262.787ms
                   - ReaderInitTime: 6.807ms
                   - RowsDelFiltered: 0
                   - RowsPushedCondFiltered: 0
                   - ScanCpuTime: 6s578ms
                   - ScanTime: 6s540ms
                   - ShowHintsTime_V1: 0ns
                  SegmentIterator:
                     - BitmapIndexFilterTimer: 2.288us
                     - BlockLoadTime: 168.981ms
                     - BlockSeekCount: 1.527K (1527)
                     - BlockSeekTime: 29.733ms
                     - BlocksLoad: 1.369K (1369)
                     - CachedPagesNum: 0
                     - CompressedBytesRead: 43.31 MB
                     - DecompressorTimer: 23.13ms
                     - IOTimer: 21.32ms
                     - IndexLoadTime_V1: 0ns
                     - NumSegmentFiltered: 8
                     - NumSegmentTotal: 14
                     - RawRowsRead: 1.4014M (1401400)
                     - RowsBitmapIndexFiltered: 0
                     - RowsBloomFilterFiltered: 3.328684M (3328684)
                     - RowsConditionsFiltered: 0
                     - RowsKeyRangeFiltered: 3.393148M (3393148)
                     - RowsStatsFiltered: 0
                     - RowsVectorPredFiltered: 0
                     - TotalPagesNum: 1.656K (1656)
                     - UncompressedBytesRead: 55.99 MB
                     - VectorPredEvalTime: 16.622ms
              HASH_JOIN_NODE (id=2):(Active: 19s802ms, % non-child: 0.02%)
                 - ExecOption: Hash Table Built Asynchronously
                 - BuildBuckets: 16.384K (16384)
                 - BuildRows: 11.125K (11125)
                 - BuildTime: 19s317ms
                 - HashTableMaxList: 5
                 - HashTableMinList: 1
                 - LoadFactor: 4602552375335452700.00
                 - PeakMemoryUsage: 4.93 MB
                 - ProbeRows: 3.556K (3556)
                 - ProbeTime: 1.71ms
                 - PushDownComputeTime: 1.949ms
                 - PushDownTime: 8.71us
                 - RowsReturned: 3.553K (3553)
                 - RowsReturnedRate: 179
                OLAP_SCAN_NODE (id=1):(Active: 19s313ms, % non-child: 72.48%)
                   - BatchQueueWaitTime: 19s313ms
                   - BytesRead: 258.06 MB
                   - NumDiskAccess: 1
                   - NumScanners: 1
                   - PeakMemoryUsage: 0.00 
                   - RowsRead: 3.579327M (3579327)
                   - RowsReturned: 11.125K (11125)
                   - RowsReturnedRate: 576
                   - ScannerBatchWaitTime: 19s314ms
                   - ScannerSchedCount : 11
                   - ScannerWorkerWaitTime: 560.983us
                   - TabletCount : 1
                   - TotalReadThroughput: 0.0 /sec
                  OlapScanner:
                     - VconjunctExprTree: null
                     - BlockConvertTime: 148.485ms
                     - BlockFetchTime: 547.243ms
                     - ReaderInitTime: 9.305ms
                     - RowsDelFiltered: 0
                     - RowsPushedCondFiltered: 0
                     - ScanCpuTime: 19s312ms
                     - ScanTime: 19s303ms
                     - ShowHintsTime_V1: 0ns
                    SegmentIterator:
                       - BitmapIndexFilterTimer: 10.287us
                       - BlockLoadTime: 394.171ms
                       - BlockSeekCount: 3.838K (3838)
                       - BlockSeekTime: 29.687ms
                       - BlocksLoad: 3.537K (3537)
                       - CachedPagesNum: 0
                       - CompressedBytesRead: 138.77 MB
                       - DecompressorTimer: 53.906ms
                       - IOTimer: 58.829ms
                       - IndexLoadTime_V1: 0ns
                       - NumSegmentFiltered: 4
                       - NumSegmentTotal: 14
                       - RawRowsRead: 3.613808M (3613808)
                       - RowsBitmapIndexFiltered: 0
                       - RowsBloomFilterFiltered: 556.682K (556682)
                       - RowsConditionsFiltered: 0
                       - RowsKeyRangeFiltered: 618.809K (618809)
                       - RowsStatsFiltered: 32.768K (32768)
                       - RowsVectorPredFiltered: 1
                       - TotalPagesNum: 3.46K (3460)
                       - UncompressedBytesRead: 171.11 MB
                       - VectorPredEvalTime: 41.1ms
                OLAP_SCAN_NODE (id=0):(Active: 484.366ms, % non-child: 1.82%)
                   - BatchQueueWaitTime: 484.126ms
                   - BytesRead: 67.68 MB
                   - NumDiskAccess: 1
                   - NumScanners: 1
                   - PeakMemoryUsage: 0.00 
                   - RowsRead: 3.556K (3556)
                   - RowsReturned: 3.556K (3556)
                   - RowsReturnedRate: 7.341K /sec
                   - ScannerBatchWaitTime: 487.879ms
                   - ScannerSchedCount : 4
                   - ScannerWorkerWaitTime: 133.337us
                   - TabletCount : 1
                   - TotalReadThroughput: 0.0 /sec
                  OlapScanner:
                     - VconjunctExprTree: null
                     - BlockConvertTime: 973.359us
                     - BlockFetchTime: 467.837ms
                     - ReaderInitTime: 9.484ms
                     - RowsDelFiltered: 0
                     - RowsPushedCondFiltered: 0
                     - ScanCpuTime: 487.698ms
                     - ScanTime: 477.730ms
                     - ShowHintsTime_V1: 0ns
                    SegmentIterator:
                       - BitmapIndexFilterTimer: 3.950us
                       - BlockLoadTime: 465.170ms
                       - BlockSeekCount: 169
                       - BlockSeekTime: 9.730ms
                       - BlocksLoad: 1.37K (1370)
                       - CachedPagesNum: 0
                       - CompressedBytesRead: 31.09 MB
                       - DecompressorTimer: 19.62ms
                       - IOTimer: 11.785ms
                       - IndexLoadTime_V1: 0ns
                       - NumSegmentFiltered: 11
                       - NumSegmentTotal: 18
                       - RawRowsRead: 1.401619M (1401619)
                       - RowsBitmapIndexFiltered: 0
                       - RowsBloomFilterFiltered: 7.401057M (7401057)
                       - RowsConditionsFiltered: 0
                       - RowsKeyRangeFiltered: 7.90736M (7907360)
                       - RowsStatsFiltered: 16.384K (16384)
                       - RowsVectorPredFiltered: 1.398063M (1398063)
                       - TotalPagesNum: 995
                       - UncompressedBytesRead: 44.03 MB
                       - VectorPredEvalTime: 380.609ms
                  RuntimeFilter:in_or_bloomfilter:
                     - RealRuntimeFilterType: bloomfilter
                     - HasPushDownToEngine: true
                     - AWaitTimeCost: 0ns
                     - EffectTimeCost: 26s131ms
```
