### DISCUSSION TITLE
Docker fails when stopping and restarting

### DISCUSSION THREAD

**Discussion by actcwlf** [apache/doris#19160] [A - General / Q&A] [answered]
使用docker镜像可以正常up，停止后再启动出现连接失败问题，与 #17286 比较类似，请问这个是什么原因？

fe日志如下
```
doris-fe  | 2023-04-27 07:52:56,232 WARN (heartbeat mgr|34) [HeartbeatMgr.runAfterCatalogReady():139] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.ConnectException: Connection refused (Connection refused), beId: 10003, beHost: 172.30.80.3, bePort: 0, httpPort: 0, brpcPort: 0
doris-fe  | 2023-04-27 07:53:01,247 WARN (heartbeat-mgr-pool-4|220) [HeartbeatMgr$BackendHeartbeatHandler.call():268] backend heartbeat got exception
doris-fe  | org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
doris-fe  |     at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[libthrift-0.13.0.jar:0.13.0]
doris-fe  |     at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:143) ~[doris-fe.jar:1.2-SNAPSHOT]
doris-fe  |     at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:126) ~[doris-fe.jar:1.2-SNAPSHOT]
doris-fe  |     at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.2.jar:2.2]
doris-fe  |     at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012) ~[commons-pool2-2.2.jar:2.2]
doris-fe  |     at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.2.jar:2.2]
doris-fe  |     at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:277) ~[commons-pool2-2.2.jar:2.2]
doris-fe  |     at org.apache.doris.common.GenericPool.borrowObject(GenericPool.java:95) ~[doris-fe.jar:1.2-SNAPSHOT]
doris-fe  |     at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:225) ~[doris-fe.jar:1.2-SNAPSHOT]
doris-fe  |     at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:203) ~[doris-fe.jar:1.2-SNAPSHOT]
doris-fe  |     at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_342]
doris-fe  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_342]
doris-fe  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_342]
doris-fe  |     at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_342]
doris-fe  | Caused by: java.net.ConnectException: Connection refused (Connection refused)
doris-fe  |     at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_342]
doris-fe  |     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_342]
doris-fe  |     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_342]
doris-fe  |     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_342]
doris-fe  |     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_342]
doris-fe  |     at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_342]
doris-fe  |     at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[libthrift-0.13.0.jar:0.13.0]
doris-fe  |     ... 13 more
doris-fe  | 2023-04-27 07:53:01,247 WARN (heartbeat mgr|34) [HeartbeatMgr.runAfterCatalogReady():139] get bad heartbeat response: type: BACKEND, status: BAD, msg: java.net.ConnectException: Connection refused (Connection refused), beId: 10003, beHost: 172.30.80.3, bePort: 0, httpPort: 0, brpcPort: 0
```
be日志如下
```
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: masterFe = 172.30.80.2
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: be_addr = 172.30.80.3:9050
doris-be  | 2023-04-27T07:30:46+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: feIpArray = 172.30.80.2
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: feEditLogPortArray = 9010
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: masterFe = 172.30.80.2:9010
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: be_addr = 172.30.80.3:9050
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: priority_networks = 172.30.80.0/24
doris-be  | 2023-04-27T07:30:46+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:31:07+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:31:07+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:31:07+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:31:27+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:31:27+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:31:27+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:31:47+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:31:47+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:31:47+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:32:08+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:32:08+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:32:08+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:32:28+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:32:28+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:32:28+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:32:49+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:32:49+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:32:49+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:33:09+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:33:09+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:33:09+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:33:29+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:33:29+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:33:29+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:33:50+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:33:50+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:33:50+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:34:10+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:34:10+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:34:10+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:34:31+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:34:31+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:34:31+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:34:51+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:34:51+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:34:51+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:35:11+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:35:11+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:35:11+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:35:32+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T07:35:32+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T07:35:32+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T07:35:52+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:36:13+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:36:33+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:36:53+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:37:14+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:37:34+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:37:55+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:38:15+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:38:36+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:38:56+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:39:16+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:39:37+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:39:57+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:40:18+00:00 [Note] [Entrypoint]: BE is not register. retry.
doris-be  | 2023-04-27T07:40:38+00:00 [Note] [Entrypoint]: BE is not register. retr
```

环境
docker image:
apache/doris:1.2.2-fe-x86_64
apache/doris:1.2.2-be-x86_64

**Comment by yagagagaga** [comment]
You need to set `sysctl -w vm.max_map_count=2000000` in your BE environment.
If you use Docker in Windows/Mac, you need to do some special operation:

## macOS with [Docker for Mac](https://docs.docker.com/docker-for-mac)

The `vm.max_map_count` setting must be set within the xhyve virtual machine:

1. From the command line, run:

```
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
```

2. Press enter and use `sysctl` to configure `vm.max_map_count`:

```
sysctl -w vm.max_map_count=2000000
```

To exit the `screen` session, type `Ctrl a d`.

## Windows and macOS with [Docker Desktop](https://www.docker.com/products/docker-desktop)

The `vm.max_map_count` setting must be set via docker-machine:

```
docker-machine ssh
sudo sysctl -w vm.max_map_count= 2000000
```

## Windows with [Docker Desktop WSL 2 backend](https://docs.docker.com/docker-for-windows/wsl)

The `vm.max_map_count` setting must be set in the "docker-desktop" WSL instance before the ElasticSearch container will properly start. There are several ways to do this, depending on your version of Windows and your version of WSL.

If you are on Windows 10 before version 22H2, or if you are on Windows 10 version 22H2 using the built-in version of WSL, you must either manually set it every time you restart Docker before starting your ElasticSearch container, or (if you do not wish to do so on every restart) you must globally set every WSL2 instance to have the `vm.max_map_count changed`. This is because these versions of WSL do not properly process the /etc/sysctl.conf file.

To manually set it every time you reboot, you must run the following commands in a command prompt or PowerShell window every time you restart Docker:

```
wsl -d docker-desktop -u root
sysctl -w vm.max_map_count=2000000
```

If you are on these versions of WSL and you do not want to have to run those commands every time you restart Docker, you can globally change every WSL distribution with this setting by modifying your %USERPROFILE%\.wslconfig as follows:

```
[wsl2]
kernelCommandLine = "sysctl.vm.max_map_count=2000000"
```

This will cause all WSL2 VMs to have that setting assigned when they start.

If you are on Windows 11, or Windows 10 version 22H2 and have installed the Microsoft Store version of WSL, you can modify the /etc/sysctl.conf within the "docker-desktop" WSL distribution, perhaps with commands like this:

```
wsl -d docker-desktop -u root
vi /etc/sysctl.conf
```

and appending a line which reads:

```
vm.max_map_count = 2000000
```

**Comment by actcwlf** [comment]
感谢回复，我已经设置了这个参数了
host
```
$ sudo sysctl -a|grep max_map_count
vm.max_map_count = 2000000
```

doris-be 容器内
```
root@be:/# sysctl -a | grep max_map_count
sysctl: reading key "kernel.unprivileged_userns_apparmor_policy"
vm.max_map_count = 2000000
```

**Reply by actcwlf** [reply]
host 是 Ubuntu20.04

**Reply by actcwlf** [reply]
另外测试中观察到首次启动再停止，再启动是可以正常启动的，但是对数据库进行写入操作后（如修改用户密码，创建数据库，导入数据）就会出现无法再次启动的问题

**Reply by yagagagaga** [reply]
Do you mean BE couldn't restart again?

**Comment by actcwlf** [comment]
我这写一下复现流程
`docker-compose.yml`如下
```
version: '3'
services:
  docker-fe:
    image: "apache/doris:1.2.2-fe-x86_64"
    container_name: "doris-fe"
    hostname: "fe1"
    environment:
      - FE_SERVERS=fe1:172.30.80.2:9010
      - FE_ID=1
    ports:
      - 8030:8030
      - 9030:9030
    volumes:
      - /data/doris/fe/doris-meta:/opt/apache-doris/fe/doris-meta
      - /data/doris/fe/conf:/opt/apache-doris/fe/conf
      - /data/doris/fe/log:/opt/apache-doris/fe/log
    logging:
      options:
        max-size: '500m'
       
    networks:
      doris_net:
        ipv4_address: 172.30.80.2
  docker-be:
    image: "apache/doris:1.2.2-be-x86_64"  # use apache/doris:1.2.1-be-x86_64-noavx2, if CPU does not support AVX2
    container_name: "doris-be"
    hostname: "be"
    depends_on:
      - docker-fe
    environment:
      - FE_SERVERS=fe1:172.30.80.2:9010
      - BE_ADDR=172.30.80.3:9050
      # ports:
      #   - 8040:8040
    volumes:
      - /data/doris/be/storage:/opt/apache-doris/be/storage
      - /data/doris/be/conf:/opt/apache-doris/be/conf
      - /data/doris/be/script:/docker-entrypoint-initdb.d
      - /data/doris/be/log:/opt/apache-doris/be/log
    logging:
      options:
        max-size: '500m'
    networks:
      doris_net:
        ipv4_address: 172.30.80.3

networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.30.80.0/16
```

1. 启动
```
docker compose up
```
可以观察到fe和be都正常启动
ctrl+c结束

2. 再次启动
```
docker compose start
```
观察日志，最终可以正常运行，mysql连接后
```
MySQL [(none)]> show backends\G;
*************************** 1. row ***************************
              BackendId: 10003
                Cluster: default_cluster
                     IP: 172.30.80.3
          HeartbeatPort: 9050
                 BePort: 9060
               HttpPort: 8040
               BrpcPort: 8060
          LastStartTime: 2023-04-27 08:51:49
          LastHeartbeat: 2023-04-27 08:53:34
                  Alive: true
   SystemDecommissioned: false
  ClusterDecommissioned: false
              TabletNum: 0
       DataUsedCapacity: 0.000 
          AvailCapacity: 1.328 TB
          TotalCapacity: 3.581 TB
                UsedPct: 62.93 %
         MaxDiskUsedPct: 62.93 %
     RemoteUsedCapacity: 0.000 
                    Tag: {"location" : "default"}
                 ErrMsg: 
                Version: doris-1.2.2-rc01-Unknown
                 Status: {"lastSuccessReportTabletsTime":"2023-04-27 08:52:58","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false}
HeartbeatFailureCounter: 0
               NodeRole: mix
1 row in set (0.01 sec)
```
```
MySQL [(none)]> SET PASSWORD FOR 'root' = PASSWORD('123456');
Query OK, 0 rows affected (0.02 sec)
```

3. 重启容器
```
docker compose restart
```

4. 观察日志
```
docker compose logs docker-be -f
```

```
doris-be  | I0427 09:16:01.075384   868 storage_engine.cpp:367] get root path info cost: 0 ms. tablet counter: 0
doris-be  | W0427 09:16:01.075603   869 utils.cpp:103] master client, retry finishTask: No more data to read.
doris-be  | I0427 09:16:01.110239   869 task_worker_pool.cpp:1519] successfully report TABLET|host=172.30.80.2|port=9020
doris-be  | I0427 09:16:01.110253   868 task_worker_pool.cpp:1519] successfully report DISK|host=172.30.80.2|port=9020
doris-be  | I0427 09:16:01.930549   867 task_worker_pool.cpp:1519] successfully report TASK|host=172.30.80.2|port=9020
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: masterFe = 172.30.80.2
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: be_addr = 172.30.80.3:9050
doris-be  | 2023-04-27T09:16:05+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: feIpArray = 172.30.80.2
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: feEditLogPortArray = 9010
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: masterFe = 172.30.80.2:9010
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: be_addr = 172.30.80.3:9050
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: priority_networks = 172.30.80.0/24
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T09:16:05+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T09:16:26+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T09:16:26+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T09:16:26+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T09:16:46+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T09:16:46+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T09:16:46+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T09:17:07+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T09:17:07+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T09:17:07+00:00 [Note] [Entrypoint]: register is failed, wait next~
doris-be  | 2023-04-27T09:17:27+00:00 [Warn] [Entrypoint]: start check be status~
doris-be  | 2023-04-27T09:17:27+00:00 [Note] [Entrypoint]: MASTER FE is not started. retry.
doris-be  | 2023-04-27T09:17:27+00:00 [Note] [Entrypoint]: register is failed, wait next~
```

这次测试观察到似乎是修改root密码触发了这个问题
