### DISCUSSION TITLE
routine load无法从kafka导入数据

### DISCUSSION THREAD

**Discussion by ztgoto** [apache/doris#7930] [A - General / Q&A]
kafka version:  2.12-2.1.0
doris version: 0.14.0 or 0.15.0
创建了一个routine load导入任务，没有看到报错信息，但数据并没有消费导入成功，不清楚是我配置问题还是怎么回事。
而且kafka 通过 kafka-consumer-groups.sh --list 看不到指定的消费组名称
```
create routine load kafka_xxx on xxx
with APPEND
columns(ts,id,name,table_name),
PRECEDING FILTER table_name='xxx'
PROPERTIES
(
  "desired_concurrent_number"="3",
  "max_batch_interval" = "20",
  "max_batch_rows" = "200000",
  "max_batch_size" = "104857600",
  "format"="json",
  "strip_outer_array"="true",
  "jsonpaths" = "[\"$.ts\",\"$.data.id\",\"$.data.name\",\"$.table\"]"

)
from KAFKA
(
  "kafka_broker_list" = "x1:9092,x2:9092,x3:9092",
  "kafka_topic" = "xxx",
  "property.group.id" = "doris-group",
  "property.client.id" = "doris"
)
```

 show routine load\G

```
*************************** 1. row ***************************
                  Id: 18009
                Name: kafka_xxx 
          CreateTime: 2022-01-28 18:00:35
           PauseTime: NULL
             EndTime: NULL
              DbName: default_cluster:xxx
           TableName: xxx
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 1
       JobProperties: {"partitions":"*","columnToColumnExpr":"ts,id,name,table_name","maxBatchIntervalS":"20","whereExpr":"*","dataFormat":"json","timezone":"Asia/Shanghai","precedingFilter":"`table_name` = 'xxx'","mergeType":"APPEND","format":"json","json_root":"","maxBatchSizeBytes":"104857600","exec_mem_limit":"2147483648","strict_mode":"false","jsonpaths":"[\"$.ts\",\"$.data.id\",\"$.data.name\",\"$.table\"]","deleteCondition":"*","desireTaskConcurrentNum":"3","maxErrorNum":"0","strip_outer_array":"true","currentTaskConcurrentNum":"1","execMemLimit":"2147483648","num_as_string":"false","fuzzy_parse":"false","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"dev.mysql.event","currentKafkaPartitions":"0,1,2","brokerList":"x1:9092,x2:9092,x3:9092"}
    CustomProperties: {"group.id":"doris-group","client.id":"doris"}
           Statistic: {"receivedBytes":0,"errorRows":0,"committedTaskNum":0,"loadedRows":0,"loadRowsRate":0,"abortedTaskNum":39,"totalRows":0,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":1}
            Progress: {"0":"OFFSET_END","1":"OFFSET_END","2":"OFFSET_END"}
ReasonOfStateChanged:
        ErrorLogUrls:
            OtherMsg:
1 row in set (0.00 sec)
```
