### ISSUE TITLE
[Bug] 官网提供的Docker Compose script无法启动

### ISSUE THREAD

**Issue by mano233** [apache/doris#17286]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1

### What's Wrong?

按照官网提供的1FE-1BE compose模板启动，BE无法注册到FE

### What You Expected?

BE报错信息如下：
```
doris-fe     | 2023-03-01 08:02:18,249 WARN (heartbeat-mgr-pool-2|142) [HeartbeatMgr$BackendHeartbeatHandler.call():268] backend heartbeat got exception
doris-fe     | org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
doris-fe     |  at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
doris-fe     |  at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:143) ~[doris-fe.jar:1.0-SNAPSHOT]
doris-fe     |  at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:126) ~[doris-fe.jar:1.0-SNAPSHOT]
doris-fe     |  at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.2.jar:2.2]
doris-fe     |  at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012) ~[commons-pool2-2.2.jar:2.2]
doris-fe     |  at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.2.jar:2.2]
doris-fe     |  at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:277) ~[commons-pool2-2.2.jar:2.2]
doris-fe     |  at org.apache.doris.common.GenericPool.borrowObject(GenericPool.java:95) ~[doris-fe.jar:1.0-SNAPSHOT]
doris-fe     |  at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:225) ~[doris-fe.jar:1.0-SNAPSHOT]
doris-fe     |  at org.apache.doris.system.HeartbeatMgr$BackendHeartbeatHandler.call(HeartbeatMgr.java:203) ~[doris-fe.jar:1.0-SNAPSHOT]
doris-fe     |  at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_342]
doris-fe     |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_342]
doris-fe     |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_342]
doris-fe     |  at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_342]
doris-fe     | Caused by: java.net.ConnectException: Connection refused (Connection refused)
doris-fe     |  at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_342]
doris-fe     |  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_342]
doris-fe     |  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_342]
doris-fe     |  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_342]
doris-fe     |  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_342]
doris-fe     |  at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_342]
doris-fe     |  at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[spark-dpp-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
doris-fe     |  ... 13 more
```
同时我观察到有如下输出：
```
doris-be     | 2023-03-01T08:01:56+00:00 [Note] [Entrypoint]: MASTER FE is started!
doris-be     | 2023-03-01T08:01:56+00:00 [Note] [Entrypoint]: add priority_networks 172.20.80.0/24 to /opt/apache-doris/be/conf/be.conf
doris-be     | 2023-03-01T08:01:56+00:00 [Note] [Entrypoint]: Register BE to FE is failed. retry.
```
但是docker-compose.yaml 里声明的cidr是：172.20.80.0/16

### How to Reproduce?

`docker-compose up`

docker-compose.yaml
```
version: '3'
services:
   docker-fe:
     image: "apache/doris:1.2.1-fe-x86_64"
     container_name: "doris-fe"
     hostname: "fe"
     environment:
       - FE_SERVERS=fe1:172.20.80.2:9010
       - FE_ID=1
     ports:
       - 8030:8030
       - 9030:9030
     volumes:
       - /data/fe/doris-meta:/opt/apache-doris/fe/doris-meta
       - /data/fe/conf:/opt/apache-doris/fe/conf
       - /data/fe/log:/opt/apache-doris/fe/log
     networks:
       doris_net:
         ipv4_address: 172.20.80.2
   docker-be:
     image: "apache/doris:1.2.1-be-x86_64"
     container_name: "doris-be"
     hostname: "be"
     depends_on:
       - docker-fe
     environment:
       - FE_SERVERS=fe1:172.20.80.2:9010
       - BE_ADDR=172.20.80.3:9050
     ports:
       - 8040:8040
     volumes:
       - /data/be/storage:/opt/apache-doris/be/storage
       - /data/be/conf:/opt/apache-doris/be/conf
       - /data/be/script:/docker-entrypoint-initdb.d
       - /data/be/log:/opt/apache-doris/be/log
     networks:
       doris_net:
         ipv4_address: 172.20.80.3
networks:
   doris_net:
     ipam:
       config:
         - subnet: 172.20.80.0/16
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
