### ISSUE TITLE
[Enhancement] Make the 'cluster' in task info for LoadStmt not empty

### ISSUE THREAD

**Issue by TangSiyang2001** [apache/doris#19222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Produce a S3 load, and run show load stmt. As seen, `cluster` is always N/A:
```
         JobId: 10131
         Label: lineitem_load
         State: LOADING
      Progress: ETL:100%; LOAD:77%
          Type: BROKER
       EtlInfo: NULL
      TaskInfo: cluster:N/A; timeout(s):14400; max_filter_ratio:0.0
      ErrorMsg: NULL
    CreateTime: 2023-04-29 12:23:29
  EtlStartTime: 2023-04-29 12:23:30
 EtlFinishTime: 2023-04-29 12:23:30
 LoadStartTime: 2023-04-29 12:23:30
LoadFinishTime: NULL
           URL: NULL
    JobDetails: {"Unfinished backends":{"de827555cbb2413d-a720be8937596b35":[10021]},"ScannedRows":36165536,"TaskNumber":1,"LoadBytes":6140395389,"All backends":{"de827555cbb2413d-a720be8937596b35":[10021]},"FileNumber":1,"FileSize":7895697364}
 TransactionId: 3
  ErrorTablets: {}
          User: root
       Comment: 
```

### Solution

Actually, the `getCluster` method in LoadStmt, as the only access to the passed in `cluster`, is never called.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
