### ISSUE TITLE
k8s部署2.0版本，开启fqdn，按照be的svc域名添加be报错[Bug] 

### ISSUE THREAD

**Issue by civic123321** [apache/doris#23382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0

### What's Wrong?

1FE 3BE 采用k8s部署，FE开启fqdn:
```
priority_networks = 10.0.0.0/8
enable_deploy_manager = k8s
enable_fqdn_mode = true
``` 

对be新建svc:
```
apiVersion: v1
kind: Service
metadata:
  name: doris-be1
  namespace: default
  labels:
    app: doris-be1
spec:
  type: NodePort
  ports:
    - port: 9060
      name: be-port
    - port: 8040
      name: webserver-port
      targetPort: 8040
      nodePort: 18040
    - port: 9050
      name: heartbeat-port #This name should be fixed. Doris will get the port information through this name
    - port: 8060
      name: brpc-port
  selector:
    app: doris-be1
``` 
使用k8s中be的虚拟域名，注册be到fe
```
ALTER SYSTEM ADD BACKEND "doris-be1.default.svc.cluster.local:9050";
``` 
fe报错，无法注册，报错信息如下:
(10.xxxx.0.xxx)[INTERNAL_ERROR]the host recorded in master is doris-be1.default.svc.cluster.local, but we cannot found the local ip that mapped to that host.10.xxx.0.xxx
10.xxx.0.xxx为be对应pod的k8s虚拟ip

### What You Expected?

为什么会报错，如何使用k8s域名注册be到fe，以保证be pod重启后，依然可以恢复数据并使用

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by civic123321** [comment]
be的svc调整为headless的service，问题解决
```
apiVersion: v1
kind: Service
metadata:
  name: doris-be1
  namespace: default
  labels:
    app: doris-be1
spec:
  #type: NodePort
  ports:
    - port: 9060
      name: be-port
    - port: 8040
      name: webserver-port
     # targetPort: 8040
     # nodePort: 18040
    - port: 9050
      name: heartbeat-port #This name should be fixed. Doris will get the port information through this name
    - port: 8060
      name: brpc-port
  clusterIP: None
  selector:
    app: doris-be1
```
