### ISSUE TITLE
[Bug] txn prepare for 3 days , it makes alter table always in WAITING_TXN

### ISSUE THREAD

**Issue by kylinmac** [apache/doris#29708]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris-1.2.6-rc03

### What's Wrong?

some txn failed to rollback  and   errors when abort txn  because of  get tableList write lock timeout
these txn status will  stay in  prepare for 3 days
when  alter these table  , State is WAITING_TXN and never change

```
[FrontendServiceImpl.loadTxnRollback():877] failed to rollback txn 33270462: errCode = 2, detailMessage = get tableList write lock timeout,

MySQL [(none)]> show transaction where id =33270462\G
*************************** 1. row ***************************
     TransactionId: 33270462
             Label: flink_connector_20240109_022324_8f18e34bbf894d54835704d8dea53d6b
       Coordinator: BE: 
 TransactionStatus: PREPARE
 LoadJobSourceType: BACKEND_STREAMING
       PrepareTime: 2024-01-09 02:23:24
     PreCommitTime: NULL
        CommitTime: NULL
       PublishTime: NULL
        FinishTime: NULL
            Reason: 
ErrorReplicasCount: 0
        ListenerId: -1
         TimeoutMs: 259200000
            ErrMsg: 
1 row in set (0.00 sec)
```

### What You Expected?

abort success , or skip this txn when alter table

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
