### ISSUE TITLE
[Bug] java.lang.RuntimeException: error in opening zip file

### ISSUE THREAD

**Issue by isiuni01** [apache/doris#45616]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

apache-doris-2.0.3-bin-arm64 on docker 

### What's Wrong?

I'm following the guide at the [link](https://doris.apache.org/docs/3.0/install/cluster-deployment/run-docker-cluster)
but I get the following error and I'm not finding any way to fix it: **java.lang.RuntimeException: error in opening zip file**

### What You Expected?

Doris BE goes UP

### How to Reproduce?

simply try to do the giude at the link above.

this are my dockerFile and docker compose :

## DockerFile BE

```
# Choose a base image
FROM openjdk:8u342-jdk

# Set environment variables
ENV JAVA_HOME="/usr/local/openjdk-8/" 
ENV PATH="/opt/apache-doris/be/bin:$PATH"

# 下Download the software into the Docker image
ADD ./resource/ApacheDoris2.0.3ARM64.tar.gz /opt/

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    apt-get clean && \
    mkdir /opt/apache-doris && \
    cd /opt && \
    mv apache-doris-2.0.3-bin-arm64/be /opt/apache-doris/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ADD ./resource/init_be.sh /opt/apache-doris/be/bin
RUN chmod 755 /opt/apache-doris/be/bin/init_be.sh

ENTRYPOINT ["/entrypoint.sh"]
```

## entrypoint.sh
```
#!/bin/sh


sysctl -w vm.max_map_count=2000001
swapoff -a

/opt/apache-doris/be/bin/init_be.sh
```

## Doris FE

```
# Choose a base image
FROM openjdk:8u342-jdk

# Set environment variables
ENV JAVA_HOME="/usr/local/openjdk-8/"
ENV PATH="/opt/apache-doris/fe/bin:$PATH"

# Download the software into the Docker image
ADD ./resource/ApacheDoris2.0.3ARM64.tar.gz /opt/

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    apt-get clean && \
    mkdir /opt/apache-doris && \
    cd /opt && \
    mv apache-doris-2.0.3-bin-arm64/fe /opt/apache-doris/

ADD ./resource/init_fe.sh /opt/apache-doris/fe/bin
RUN chmod 755 /opt/apache-doris/fe/bin/init_fe.sh

ENTRYPOINT ["/opt/apache-doris/fe/bin/init_fe.sh"]
```

## docker-compose
```

services:
  fe:
    image: doris-fe
    hostname: fe
    environment:
     - FE_SERVERS=fe1:172.0.0.1:9010
     - FE_ID=1
    volumes:
     - fe:/opt/apache-doris/fe/doris-meta/
     - fe:/opt/apache-doris/fe/log/
    network_mode: host
  be:
    image: doris-be
    hostname: be
    environment:
     - FE_SERVERS=fe1:172.0.0.1:9010
     - BE_ADDR=172.0.0.1:9050
    volumes:
     - be:/opt/apache-doris/be/storage/
     - be:/docker-entrypoint-initdb.d/
    depends_on:
      - fe
    network_mode: host
    privileged: true 
    


volumes:
  fe:
  be:
```

**i had to change volume managing so they are differente to the docker-compose in the documentation due to issue of docker on macOS**
 thx <3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
