### ISSUE TITLE
[Bug] doris 3.x audit log scan_bytes_from_local_storage/scan_bytes_from_remote_storage is incorrect

### ISSUE THREAD

**Issue by wenzhenghu** [apache/doris#51872]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 3.x

### What's Wrong?

```
*************************** 1. row ***************************
                      query_id: 79305c291e524880-a38a8823f3df7a1c
                          time: 2025-06-04 08:48:46.124
                     client_ip: 192.168.65.3:55348
                          user: root
                       catalog: hive
                            db: tpch
                         state: EOF
                    error_code: 0
                 error_message:
                    query_time: 121
                    scan_bytes: 58762816
                     scan_rows: 207820
                   return_rows: 10
             shuffle_send_rows: 0
            shuffle_send_bytes: 0
 scan_bytes_from_local_storage: 0
scan_bytes_from_remote_storage: 0
                       stmt_id: 29
                     stmt_type: SELECT
                      is_query: 1
                    is_nereids: 1
                   frontend_ip: 192.168.65.3
                   cpu_time_ms: 16
                      sql_hash: 5947943d6a31e3ab9d33fb083906f664
                    sql_digest:
             peak_memory_bytes: 48109260
                workload_group: normal
                 compute_group: UNKNOWN
                          stmt: select     l_orderkey,     sum(l_extendedprice * (1 - l_discount)) as revenue,     o_orderdate,     o_shippriority from     customer,     orders,     lineitem where     c_mktsegment = 'BUILDING'     and c_custkey = o_custkey     and l_orderkey = o_orderkey     and o_orderdate < date '1995-03-15'     and l_shipdate > date '1995-03-15' group by     l_orderkey,     o_orderdate,     o_shippriority order by     revenue desc,     o_orderdate limit 10
```

 scan_bytes_from_local_storage and scan_bytes_from_remote_storage is zero,  should be scan_bytes = scan_bytes_from_local_storage + scan_bytes_from_remote_storage

### What You Expected?

scan_bytes = scan_bytes_from_local_storage + scan_bytes_from_remote_storage

### How to Reproduce?

run a hive catalog tpch test, and select the audit_log table

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
