### ISSUE TITLE
[Bug] Doris benchmark data run failed with buffer overflow detected

### ISSUE THREAD

**Issue by HackToday** [apache/doris#7833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

version： trunk 4768dd4efa7f6fb87e160809b37ce542ba9c0531

### What's Wrong?

执行 https://github.com/apache/incubator-doris/blob/master/docs/zh-CN/benchmark/star-schema-benchmark.md
压测，
环境是： Ubuntu 20.04.3 LTS

```
*************************** 1. row ***************************
            BackendId: 10002
              Cluster: default_cluster
                   IP: xx.xx.xx.xx
             HostName: xx.xx.xx.xx
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
             BrpcPort: 8060
        LastStartTime: 2022-01-21 09:06:27
        LastHeartbeat: 2022-01-21 09:18:06
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 40
     DataUsedCapacity: 0.000
        AvailCapacity: 866.386 GB
        TotalCapacity: 915.891 GB
              UsedPct: 5.41 %
       MaxDiskUsedPct: 5.41 %
                  Tag: {"location" : "default"}
               ErrMsg:
              Version: trunk-4768dd4
               Status: {"lastSuccessReportTabletsTime":"2022-01-21 09:17:08","lastStreamLoadTime":-1,"isQueryDisabled":false,"isLoadDisabled":false}
```

创建表可以正常操作没有问题，
但是执行 ssb benchmark 会出现如下的错误：

```
Scale Factor: 100
Parallelism: 100
Begin to generate data for table: customer
SSBM (Star Schema Benchmark) Population Generator (Version 1.0.0)
Copyright Transaction Processing Performance Council 1994 - 2000
Begin to generate data for table: part
SSBM (Star Schema Benchmark) Population Generator (Version 1.0.0)
Copyright Transaction Processing Performance Council 1994 - 2000
Begin to generate data for table: supplier
SSBM (Star Schema Benchmark) Population Generator (Version 1.0.0)
Copyright Transaction Processing Performance Council 1994 - 2000
Begin to generate data for table: date
SSBM (Star Schema Benchmark) Population Generator (Version 1.0.0)
Copyright Transaction Processing Performance Council 1994 - 2000
Begin to generate data for table: lineorder
SSBM (Star Schema Benchmark) Population Generator (Version 1.0.0)
Copyright Transaction Processing Performance Council 1994 - 2000
*** buffer overflow detected ***: terminated
*** buffer overflow detected ***: terminated
*** buffer overflow detected ***: terminated
*** buffer overflow detected ***: terminated
*** buffer overflow detected ***: terminated
*** buffer overflow detected ***: terminated
*** buffer overflow detected ***: terminated
*** buffer overflow detected ***: terminated
```

The log for FE and BE not have any special errors.

### What You Expected?

执行 sh gen-ssb-data.sh -s 100 -c 100 正常，没有错误

### How to Reproduce?

1. 使用最新的 docker 镜像 build Doris
2. 配置 FE 和 BE，并且启动
3. 执行 benchmark 在一台配置尽量高的机器上。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
